// <auto-generated />
using ApiOderService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ApiOderService.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20180419043438_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("ApiOderService.Buyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Addr");

                    b.Property<string>("Email");

                    b.Property<string>("RealName");

                    b.Property<string>("UserID");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Buyer");
                });

            modelBuilder.Entity("ApiOderService.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BuyerId");

                    b.Property<DateTime>("CreateDate");

                    b.Property<decimal>("DeliverFee");

                    b.Property<sbyte?>("Delivery");

                    b.Property<sbyte?>("IsConfirm");

                    b.Property<sbyte>("IsPaiy");

                    b.Property<string>("Note");

                    b.Property<string>("Oid");

                    b.Property<double>("PayableFee");

                    b.Property<sbyte?>("PaymentCash");

                    b.Property<sbyte>("PaymentWay");

                    b.Property<sbyte>("State");

                    b.Property<double>("TotalPrice");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("ApiOderService.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<string>("Color");

                    b.Property<int>("OrderId");

                    b.Property<string>("ProductName");

                    b.Property<string>("ProductNo");

                    b.Property<string>("Size");

                    b.Property<double>("SkuPrice");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("ApiOderService.OrderItem", b =>
                {
                    b.HasOne("ApiOderService.Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
